### ISSUE TITLE
How to display string content?

### ISSUE THREAD

**Issue by mrhanCH** [benjohnemmett/Hub75MicroPython#11]
Hello, great job.
May I ask if you have a suitable method for displaying English words or Chinese characters?
Thank you!

**Comment by benjohnemmett** [comment]
I haven't done any character support in this library. You might look at this related project that displays the time. https://github.com/danielmader/MatrixClock_MicroPythonESP

**Comment by mrhanCH** [comment]
thanks
&nbsp;


Mr.Han
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Ben ***@***.***&gt;; 
发送时间: 2024年5月25日(星期六) 中午11:54
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [benjohnemmett/Hub75MicroPython] How to display string content? (Issue #11)















我没有在这个库中做过任何字符支持。您可以查看这个显示时间的相关项目。https://github.com/danielmader/MatrixClock_MicroPythonESP

-
直接回复这封邮件，在GitHub上查看，或取消订阅.
***@***.***和&gt;
